import localFont from "next/font/local";
import "./globals.css";

const gilroyMedium = localFont({
  src: "./fonts/Gilroy-Medium.ttf",
  variable: "--font-gilroy-medium",
});

const gilroyRregular = localFont({
  src: "./fonts/Gilroy-Regular.ttf",
  variable: "--font-gilroy-regular",
});

export const metadata = {
  title: "Studia Beta Tester",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />

      <body
        className={`${gilroyRregular.variable} ${gilroyMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
